[general]
import = [
  "~/dotfiles/alacritty/kanagawa.toml",
]

[window]
opacity=0.9
padding.x = 2
decorations = "None"

[scrolling]
history = 100000

[font]
normal.family = "Iosevka Term"
normal.style = "medium"
size = 12

[terminal]
shell.program = "/usr/bin/fish"

[env]
term = "xterm-256color"

[cursor]
style.shape = "Underline"
style.blinking = "Always"
