[general]
import = [
  "~/dotfiles/alacritty/kanagawa.toml",
]

[window]
opacity=0.92
padding.x = 2

[scrolling]
history = 100000

[font]
normal.family = "Iosevka Term"
normal.style = "semibold"
size = 12

[terminal]
shell.program = "/usr/bin/fish"

[env]
term = "xterm-256color"

[cursor]
style.shape = "Underline"
style.blinking = "Always"
