#! /usr/bin/fish
grim -g (swaymsg -t get_tree | jq -j '.. | select(.type?) | select(.focused).rect | "\(.x),\(.y) \(.width)x\(.height)"') - | wl-copy -t image/png
notify-send "Focused pane saved to clipboard"
