[user]
name = "Sam Praneis"
email = "spraneis@wolve.com"

[ui]
editor = "nvim"
graph.style = "square"
default-command = "log"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
logr = ["log", "-r"]


[colors]
"diff token" = { underline = false }
"diff removed token" = { bg = "#221111" }
"diff added token" = { bg = "#002200" }
