[rust]
symbol = "[ ](bright-yellow)"


[git_branch]
format = "on [$symbol $branch(:$remote_branch)]($style) "
symbol = ""

[git_commit]
commit_hash_length = 7
format = '[\($hash$tag\)]($style) '
style = "green bold"
only_detached = false
disabled = false

[git_state]
style = "yellow"

[git_status]
format = '([\[ $all_status$ahead_behind\]]($style) )'
style = "red"
ahead = "⇡$count "
behind = "⇣$count "
up_to_date = ""
diverged = "⇕$count "
conflicted = "=$count "
deleted = "✘$count "
renamed = "»$count "
modified = "󱇧$count "
staged = "+$count "
untracked = "󱀶$count "

